### ISSUE TITLE
Concept 05: Multi View Geometry - Assignment

### ISSUE THREAD

**Issue by RahulSajnani** [RoboticsIIITH/summer-sessions-2020#22]
MVG assignment is uploaded [here](https://www.notion.so/Assignment-on-MVG-6fe658ee824f416a9b48850973eaef8d). The instructions on how to submit your answers along with the deadline will be updated in the page itself, for now, you can get started with solving the questions.

**Comment by Shubodh** [comment]
Instructions have been updated on the same page. The deadline is 10/06.

You will not be given any assignment on SLAM or state estimation. So we feel 4 days would be sufficient. However, if it is still not sufficient, please let us know.

**Comment by RahulSajnani** [comment]
Clarification: The translation mentioned in the doc are in cms whereas the scale of lidar points are in metres. So while creating your translation matrix divide the values by 100. 27 -> 0.27, 6-> 0.06 etc.

**Comment by Shubodh** [comment]
The assignment deadline has been extended by 4 days - the new deadline is 14/06. We will have a short discussion session on 15/06.

**Comment by Shubodh** [comment]
Fill this [form](https://forms.office.com/Pages/ResponsePage.aspx?id=vDsaA3zPK06W7IZ1VVQKHJbn0dkSCedGgFAxJH5sQDJURjJQMFRFM1dXQkNLU0IwMlVYQlBKTkVNMy4u) for submission of your assignment (filling Notion link for theory questions). Email Rahul the coding questions. Enable comment access so that we can share feedback. (Share → Show link options → Allow comments)

Also, please look at [this page](https://www.notion.so/Assignment-on-MVG-6fe658ee824f416a9b48850973eaef8d) again before submission (if you duplicated it long back) for more recent instructions.

**Comment by Shubodh** [comment]
I'm keeping the form open till today noon, if anyone missed the deadline they can still submit.

Also, 1 or 2 students invited me to the page. Instead, please click on "Share to the page" on "Share" at the top right of the page and enable comment access. Please follow instructions [here](https://www.notion.so/saishubodh/Assignment-on-MVG-6fe658ee824f416a9b48850973eaef8d#7198d39b52c74810835882f949f04a82). You need not fill the form again, just change the permissions of that same page.
